;;; howm-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from action-lock.el

(register-definition-prefixes "action-lock" '("action-lock-"))


;;; Generated autoloads from cheat-font-lock.el

(register-definition-prefixes "cheat-font-lock" '("cheat-font-lock-"))


;;; Generated autoloads from gfunc.el

(register-definition-prefixes "gfunc" '("*gfunc-dispatchers-var*" "gfunc-"))


;;; Generated autoloads from honest-report.el

(register-definition-prefixes "honest-report" '("honest-report"))


;;; Generated autoloads from howm.el

(register-definition-prefixes "howm" '("howm-version"))


;;; Generated autoloads from howm-backend.el

(register-definition-prefixes "howm-backend" '("*howm-" "action-lock-find-file" "howm-"))


;;; Generated autoloads from howm-common.el

(register-definition-prefixes "howm-common" '("*howm-view-in-background*" "howm-"))


;;; Generated autoloads from howm-date.el

(register-definition-prefixes "howm-date" '("howm-"))


;;; Generated autoloads from howm-lang-en.el

(register-definition-prefixes "howm-lang-en" '("howm-"))


;;; Generated autoloads from howm-lang-fr.el

(register-definition-prefixes "howm-lang-fr" '("howm-"))


;;; Generated autoloads from howm-lang-ja.el

(register-definition-prefixes "howm-lang-ja" '("howm-"))


;;; Generated autoloads from howm-menu.el

(register-definition-prefixes "howm-menu" '("*howm-menu-" "howm-"))


;;; Generated autoloads from howm-misc.el

(register-definition-prefixes "howm-misc" '("action-lock-mode-before-canna" "auto-save-buffers" "canna:" "howm-" "mcomplete-p"))


;;; Generated autoloads from howm-mkmenu.el

(register-definition-prefixes "howm-mkmenu" '("howm-mkmenu"))


;;; Generated autoloads from howm-mode.el

(register-definition-prefixes "howm-mode" '("*howm-" "howm-"))


;;; Generated autoloads from howm-reminder.el

(register-definition-prefixes "howm-reminder" '("howm-"))


;;; Generated autoloads from howm-vars.el

(register-definition-prefixes "howm-vars" '("howm-"))


;;; Generated autoloads from howm-view.el

(register-definition-prefixes "howm-view" '("*howm-" "howm-" "riffle-"))


;;; Generated autoloads from iigrep.el

(register-definition-prefixes "iigrep" '("*iigrep-" "iigrep"))


;;; Generated autoloads from illusion.el

(register-definition-prefixes "illusion" '("illusion-" "yarot13-"))


;;; Generated autoloads from riffle.el

(register-definition-prefixes "riffle" '("*riffle-" "even-window-heights" "howm-view-" "riffle-"))

;;; End of scraped data

(provide 'howm-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; howm-autoloads.el ends here
