;;; undohist-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from undohist.el

(autoload 'undohist-initialize "undohist" "\
Initialize undo history facilities.
To use undohist, you just call this function." t)
(register-definition-prefixes "undohist" '("make-undohist-file-name" "undohist-"))

;;; End of scraped data

(provide 'undohist-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; undohist-autoloads.el ends here
