;;; real-auto-save-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from real-auto-save.el

(autoload 'real-auto-save-turn-on "real-auto-save" "\
Turn on Real-Auto-Save Mode for current if it's visiting a file.

This function is designed to be added to hooks, for example:
  (add-hook \\='c-mode-hook #\\='real-auto-save-turn-turn-on)")
(autoload 'real-auto-save-turn-off "real-auto-save" "\
Turn off Real-Auto-Save Mode.

This function is designed to be added to hooks, for example:
  (add-hook \\='message-mode-hook #\\='real-auto-save-turn-off)

Useful in combination when `global-real-auto-save-mode' is used to
opt-out of auto-saving on a per-buffer or per-mode basis.")
(autoload 'real-auto-save-mode "real-auto-save" "\
Save your buffers automatically.

This is a minor mode.  If called interactively, toggle the
`Real-Auto-Save mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `real-auto-save-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(put 'global-real-auto-save-mode 'globalized-minor-mode t)
(defvar global-real-auto-save-mode nil "\
Non-nil if Global Real-Auto-Save mode is enabled.
See the `global-real-auto-save-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-real-auto-save-mode'.")
(custom-autoload 'global-real-auto-save-mode "real-auto-save" nil)
(autoload 'global-real-auto-save-mode "real-auto-save" "\
Toggle Real-Auto-Save mode in all buffers.
With prefix ARG, enable Global Real-Auto-Save mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Real-Auto-Save mode is enabled in all buffers where
`real-auto-save-turn-on' would do it.

See `real-auto-save-mode' for more information on Real-Auto-Save
mode.

(fn &optional ARG)" t)
(register-definition-prefixes "real-auto-save" '("real-auto-save-"))

;;; End of scraped data

(provide 'real-auto-save-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; real-auto-save-autoloads.el ends here
